export const RankingParams = {
    weights: {
        distance: 0.25,
        followers: 0.2,
        verification: 0.15,
        profilePicture: 0.1,
        relationWeight: 0.15,
        premium: 0.05,
        mutualFollow: 0.2,
        followYou: 0.1,
        youFollow: 0.05,
        blockYou: -0.5,
    },
    factors: {
        maxDistance: 50,
        minFollowers: 0,
        maxFollowers: 1000000,
        boostVerified: true,
        boostPremium: true,
        penalizeBlocked: true,
        penalizeMuted: true,
        boostMutualFollow: true,
        boostFollowYou: true,
        penalizeYouFollow: false,
    },
}
